[workspace]
authors = ["beautiful <135546587+Greg4268@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "PersonalNetworkPing"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
hilbertcurve = ">=2.0.5,<3"
matplotlib = ">=3.10.6,<4"
numpy = ">=2.3.3,<3"
netifaces = ">=0.11.0,<0.12"
